import { useEffect, useMemo, useState } from 'react';
import { Button, DatePicker, Input, Popconfirm, Select, Space, Table, Typography, message } from 'antd';
import dayjs from 'dayjs';
import { ApiClient } from '../api/apiClient.js';
import { useApp } from '../AppContext.jsx';

const { RangePicker } = DatePicker;

const { Title } = Typography;

export default function FinalReportListView() {
  const { user, openCase } = useApp();
  const isAdmin = user?.role === 'admin';

  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(false);
  const [busyId, setBusyId] = useState(null);
  const [search, setSearch] = useState('');
  const [officerFilter, setOfficerFilter] = useState();
  const [dateRange, setDateRange] = useState(null);

  useEffect(() => {
    load();
  }, []);

  const officerOptions = useMemo(() => {
    const names = [...new Set(rows.map((r) => r.generated_by_name).filter(Boolean))];
    return names.sort().map((name) => ({ label: name, value: name }));
  }, [rows]);

  const filteredRows = useMemo(() => {
    const q = search.trim().toLowerCase();
    return rows.filter((r) => {
      if (q) {
        const hay = `${r.probationer_name || ''} ${r.docket_number || ''}`.toLowerCase();
        if (!hay.includes(q)) return false;
      }
      if (officerFilter && r.generated_by_name !== officerFilter) return false;
      if (dateRange && dateRange[0] && dateRange[1]) {
        const generated = dayjs(r.generated_at);
        if (generated.isBefore(dateRange[0], 'day') || generated.isAfter(dateRange[1], 'day')) return false;
      }
      return true;
    });
  }, [rows, search, officerFilter, dateRange]);

  async function load() {
    setLoading(true);
    try {
      setRows(await ApiClient.get('/file-reports'));
    } catch (err) {
      message.error(err.message);
    } finally {
      setLoading(false);
    }
  }

  async function openFile(id) {
    setBusyId(id);
    try {
      const { base64, filename } = await ApiClient.get(`/file-reports/${id}/download`);
      await window.api.fileReportOpenFile(base64, filename);
    } catch (err) {
      message.error(err.message);
    } finally {
      setBusyId(null);
    }
  }

  async function saveFileAs(id) {
    setBusyId(id);
    try {
      const { base64, filename } = await ApiClient.get(`/file-reports/${id}/download`);
      const result = await window.api.fileReportSaveFile(base64, filename);
      if (result.ok) message.success(`Saved to ${result.filePath}`);
    } catch (err) {
      message.error(err.message);
    } finally {
      setBusyId(null);
    }
  }

  async function remove(id) {
    try {
      await ApiClient.delete(`/file-reports/${id}`);
      message.success('Deleted.');
      await load();
    } catch (err) {
      message.error(err.message);
    }
  }

  return (
    <div>
      <Title level={3} style={{ margin: '0 0 16px' }}>Final Reports</Title>

      <Space wrap style={{ marginBottom: 16 }}>
        <Input.Search
          placeholder="Search name or docket #…"
          allowClear
          style={{ width: 280 }}
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <Select
          placeholder="All Officers"
          allowClear
          style={{ width: 220 }}
          options={officerOptions}
          value={officerFilter}
          onChange={setOfficerFilter}
        />
        <RangePicker
          placeholder={['Generated from', 'Generated to']}
          value={dateRange}
          onChange={setDateRange}
        />
      </Space>

      <Table
        rowKey="id"
        loading={loading}
        dataSource={filteredRows}
        columns={[
          {
            title: 'Probationer',
            dataIndex: 'probationer_name',
            key: 'probationer_name',
            render: (name, row) => <a onClick={() => openCase(row.probationer_id)}>{name}</a>,
          },
          { title: 'Docket #', dataIndex: 'docket_number', key: 'docket_number' },
          {
            title: 'Generated',
            dataIndex: 'generated_at',
            key: 'generated_at',
            render: (v) => new Date(v).toLocaleString(),
          },
          { title: 'Generated By', dataIndex: 'generated_by_name', key: 'generated_by_name' },
          {
            title: 'Actions',
            key: 'actions',
            render: (_, row) => (
              <Space>
                <Button size="small" loading={busyId === row.id} onClick={() => openFile(row.id)}>Open</Button>
                <Button size="small" loading={busyId === row.id} onClick={() => saveFileAs(row.id)}>Save a copy as…</Button>
                {isAdmin && (
                  <Popconfirm title="Delete this Final Report?" onConfirm={() => remove(row.id)}>
                    <Button size="small" danger>Delete</Button>
                  </Popconfirm>
                )}
              </Space>
            ),
          },
        ]}
      />
    </div>
  );
}
