import { useEffect, useMemo, useRef, useState } from 'react';
import { Button, DatePicker, Input, Popconfirm, Select, Space, Table, Tabs, Tag, Tooltip, Typography, message } from 'antd';
import { LockOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { ApiClient } from '../api/apiClient.js';
import { useApp } from '../AppContext.jsx';
import { useDocEditor, lockStatus } from '../hooks/useDocEditor.js';
import { composeName } from '../utils/composeName.js';

const { RangePicker } = DatePicker;
const { Title, Text } = Typography;

// Maps a probationer (+ its psir_profile snapshot) onto the exact record
// shape renderer/public/records-check-generator/rc-render.js expects — see
// its FIELDS table. Birthdate is sent as a real Date (postMessage's
// structured clone preserves Date instances) since rc-render's fmtDate()
// only recognizes Date objects or Excel serial numbers, not ISO strings.
// LAST_NAME/FIRST_NAME/MIDDLE_NAME aren't part of that FIELDS table — they
// ride along just for the saved PDF's filename (see app-logic.js).
function buildRec(p) {
  const profile = p.psir_profile || {};
  const f = profile.fields || {};
  // Prefer the stored name parts; fall back to the psir_profile snapshot only
  // when the columns are somehow blank (e.g. an old snapshot edited by hand).
  const name = (p.last_name || p.first_name || p.middle_name)
    ? { lastName: p.last_name || '', firstName: p.first_name || '', middleName: p.middle_name || '' }
    : { lastName: f.lastName || '', firstName: f.firstName || '', middleName: f.middleName || '' };
  return {
    NAME: composeName(p),
    'TRUE NAME': f.trueName || '',
    ALIAS: p.alias || '',
    SEX: p.sex || '',
    AGE: p.age != null ? String(p.age) : '',
    'CIVIL STATUS': p.marital_status || '',
    'DATE OF BIRTH': p.birthdate ? new Date(p.birthdate) : null,
    'PLACE OF BIRTH': '',
    'PRESENT ADDRESS': p.address || '',
    'PERMANENT ADDRESS': f.permanentAddress || p.address || '',
    'CRIMINAL CASE NO./S': p.case_number || '',
    OFFENSES: p.offense || '',
    COURT: p.court_branch || '',
    'NAME OF SPOUSE': f.spouse || '',
    'NAME OF FATHER': f.fatherName || '',
    'NAME OF MOTHER': f.motherName || '',
    IO: p.assigned_officer_name || '',
    BARANGAY: '',
    LAST_NAME: name.lastName,
    FIRST_NAME: name.firstName,
    MIDDLE_NAME: name.middleName,
  };
}

function GeneratorTab({ iframeRef, count, loading, onRefresh }) {
  return (
    <div>
      <Space align="center" style={{ width: '100%', justifyContent: 'space-between', marginBottom: 12 }}>
        <Text type="secondary" style={{ fontSize: 13 }}>
          {count} case{count === 1 ? '' : 's'} available — queue petitioners below, then save PDFs and/or print.
        </Text>
        <Button onClick={onRefresh} loading={loading}>Refresh Case List</Button>
      </Space>
      <div style={{ height: 'calc(100vh - 220px)', border: '1px solid #e6e9ee', borderRadius: 6, overflow: 'hidden' }}>
        <iframe
          ref={iframeRef}
          title="Records Check Generator"
          src="records-check-generator/index.html"
          style={{ width: '100%', height: '100%', border: 'none' }}
        />
      </div>
    </div>
  );
}

function SavedFilesTab({ rows, loading, busyId, isAdmin, userId, editor, onRefresh, onOpen, onSaveAs, onDelete, onForceUnlock }) {
  const [search, setSearch] = useState('');
  const [officerFilter, setOfficerFilter] = useState();
  const [dateRange, setDateRange] = useState(null);

  const officerOptions = useMemo(() => {
    const names = [...new Set(rows.map((r) => r.generated_by_name).filter(Boolean))];
    return names.sort().map((name) => ({ label: name, value: name }));
  }, [rows]);

  const filteredRows = useMemo(() => {
    const q = search.trim().toLowerCase();
    return rows.filter((r) => {
      if (q) {
        const hay = `${r.probationer_name || ''} ${r.docket_number || ''}`.toLowerCase();
        if (!hay.includes(q)) return false;
      }
      if (officerFilter && r.generated_by_name !== officerFilter) return false;
      if (dateRange && dateRange[0] && dateRange[1]) {
        const generated = dayjs(r.generated_at);
        if (generated.isBefore(dateRange[0], 'day') || generated.isAfter(dateRange[1], 'day')) return false;
      }
      return true;
    });
  }, [rows, search, officerFilter, dateRange]);

  const recipients = [...new Set(filteredRows.map((r) => r.recipient))].sort();

  const columns = [
    {
      title: 'Date', dataIndex: 'date_folder', key: 'date_folder', width: 120,
      sorter: (a, b) => a.date_folder.localeCompare(b.date_folder),
    },
    { title: 'Petitioner', dataIndex: 'probationer_name', key: 'probationer_name' },
    { title: 'Docket #', dataIndex: 'docket_number', key: 'docket_number', width: 150 },
    { title: 'Generated By', dataIndex: 'generated_by_name', key: 'generated_by_name', width: 170 },
    {
      title: 'Generated', dataIndex: 'generated_at', key: 'generated_at', width: 180,
      render: (v) => new Date(v).toLocaleString(),
      sorter: (a, b) => new Date(a.generated_at) - new Date(b.generated_at), defaultSortOrder: 'descend',
    },
    {
      title: 'Actions', key: 'actions', width: 360,
      render: (_, row) => {
        const lock = lockStatus(row, userId);
        const mine = editor.isEditing(row.id) || (lock.locked && lock.byMe);
        const lockedByOther = lock.locked && !lock.byMe;
        const canDelete = isAdmin || row.generated_by === userId;
        return (
          <Space wrap>
            <Button size="small" loading={busyId === row.id} onClick={() => onOpen(row.id)}>Open (read-only)</Button>
            {mine ? (
              <Button size="small" type="primary" loading={editor.busyId === row.id} onClick={() => editor.stopEdit(row.id)}>
                Done editing
              </Button>
            ) : lockedByOther ? (
              <Tooltip title={`Being edited by ${lock.name || 'another user'}`}>
                <Tag icon={<LockOutlined />} color="orange">In use{lock.name ? ` — ${lock.name}` : ''}</Tag>
              </Tooltip>
            ) : (
              <Button size="small" loading={editor.busyId === row.id} onClick={() => editor.startEdit(row.id)}>Edit</Button>
            )}
            <Button size="small" loading={busyId === row.id} onClick={() => onSaveAs(row.id)}>Save a copy as…</Button>
            {isAdmin && lockedByOther && (
              <Popconfirm title={`Force-release ${lock.name || 'this'} lock?`} onConfirm={() => onForceUnlock(row.id)}>
                <Button size="small" danger>Force unlock</Button>
              </Popconfirm>
            )}
            {canDelete && (
              <Popconfirm title="Delete this file?" onConfirm={() => onDelete(row.id)}>
                <Button size="small" danger>Delete</Button>
              </Popconfirm>
            )}
          </Space>
        );
      },
    },
  ];

  const hasFilters = Boolean(search.trim() || officerFilter || (dateRange && dateRange[0] && dateRange[1]));

  return (
    <div>
      <Space align="center" style={{ width: '100%', justifyContent: 'space-between', marginBottom: 12 }}>
        <Text type="secondary" style={{ fontSize: 13 }}>
          Shared across Head Office and Branch Office — {filteredRows.length} file{filteredRows.length === 1 ? '' : 's'} across {recipients.length} folder{recipients.length === 1 ? '' : 's'}
          {hasFilters ? ` (of ${rows.length} total)` : ''}.
        </Text>
        <Button onClick={onRefresh} loading={loading}>Refresh</Button>
      </Space>

      <Space wrap style={{ marginBottom: 16 }}>
        <Input.Search
          placeholder="Search name or docket #…"
          allowClear
          style={{ width: 280 }}
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <Select
          placeholder="All Officers"
          allowClear
          style={{ width: 220 }}
          options={officerOptions}
          value={officerFilter}
          onChange={setOfficerFilter}
        />
        <RangePicker
          placeholder={['Generated from', 'Generated to']}
          value={dateRange}
          onChange={setDateRange}
        />
      </Space>

      {recipients.length === 0 ? (
        <Text type="secondary">
          {rows.length === 0
            ? 'No PDFs saved yet — use the Generator tab to save some.'
            : 'No files match the current filters.'}
        </Text>
      ) : (
        <Tabs
          type="card"
          items={recipients.map((recipient) => {
            const recipientRows = filteredRows.filter((r) => r.recipient === recipient);
            return {
              key: recipient,
              label: `${recipient} (${recipientRows.length})`,
              children: (
                <Table
                  rowKey="id"
                  loading={loading}
                  dataSource={recipientRows}
                  pagination={{ pageSize: 20 }}
                  columns={columns}
                />
              ),
            };
          })}
        />
      )}
    </div>
  );
}

export default function RecordsCheckView() {
  const { user } = useApp();
  const isAdmin = user?.role === 'admin';
  const iframeRef = useRef(null);
  const [loading, setLoading] = useState(false);
  const [count, setCount] = useState(0);
  const [files, setFiles] = useState([]);
  const [filesLoading, setFilesLoading] = useState(false);
  const [busyId, setBusyId] = useState(null);

  async function loadAndSend() {
    setLoading(true);
    try {
      const probationers = await ApiClient.get('/probationers');
      const list = probationers.map((p) => ({ id: String(p.id), name: composeName(p) }));
      const rows = {};
      probationers.forEach((p) => { rows[String(p.id)] = buildRec(p); });
      setCount(list.length);
      iframeRef.current?.contentWindow?.postMessage({ type: 'rc:setMasterlist', payload: { list, rows } }, '*');
    } catch (err) {
      message.error(err.message);
    } finally {
      setLoading(false);
    }
  }

  async function loadFiles() {
    setFilesLoading(true);
    try {
      setFiles(await ApiClient.get('/records-check'));
    } catch (err) {
      message.error(err.message);
    } finally {
      setFilesLoading(false);
    }
  }

  async function openFile(id) {
    setBusyId(id);
    try {
      const { base64, filename } = await ApiClient.get(`/records-check/${id}/download`);
      await window.api.recordsCheckOpenFile(base64, filename);
    } catch (err) {
      message.error(err.message);
    } finally {
      setBusyId(null);
    }
  }

  async function saveFileAs(id) {
    setBusyId(id);
    try {
      const { base64, filename } = await ApiClient.get(`/records-check/${id}/download`);
      const result = await window.api.recordsCheckSaveFile(base64, filename);
      if (result.ok) message.success(`Saved to ${result.filePath}`);
    } catch (err) {
      message.error(err.message);
    } finally {
      setBusyId(null);
    }
  }

  async function deleteFile(id) {
    try {
      await ApiClient.delete(`/records-check/${id}`);
      message.success('Deleted.');
      await loadFiles();
    } catch (err) {
      message.error(err.message);
    }
  }

  const editor = useDocEditor({
    keyPrefix: 'records-check',
    lockPath: (id) => `/records-check/${id}/lock`,
    uploadPath: (id) => `/records-check/${id}/file`,
    downloadFile: (id) => ApiClient.get(`/records-check/${id}/download`),
    onReleased: loadFiles,
  });

  async function forceUnlock(id) {
    try {
      await ApiClient.delete(`/records-check/${id}/lock`);
      message.success('Lock released.');
      await loadFiles();
    } catch (err) {
      message.error(err.message);
    }
  }

  useEffect(() => {
    loadFiles();
  }, []);

  useEffect(() => {
    function handleMessage(ev) {
      if (!iframeRef.current || ev.source !== iframeRef.current.contentWindow) return;
      const msg = ev.data;
      if (!msg || typeof msg !== 'object') return;

      if (msg.type === 'rc:ready') {
        loadAndSend();
      } else if (msg.type === 'rc:savePdfs') {
        const { files: toSave } = msg.payload || {};
        ApiClient.post('/records-check/batch', { files: toSave })
          .then((result) => {
            iframeRef.current?.contentWindow?.postMessage({ type: 'rc:saveResult', payload: { ok: true, count: result.count } }, '*');
            loadFiles();
          })
          .catch((err) => {
            iframeRef.current?.contentWindow?.postMessage({ type: 'rc:saveResult', payload: { ok: false, error: err.message } }, '*');
          });
      }
    }
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div>
      <Title level={3} style={{ margin: '0 0 12px' }}>Records Check</Title>
      <Tabs
        defaultActiveKey="generator"
        items={[
          {
            key: 'generator',
            label: 'Generator',
            children: <GeneratorTab iframeRef={iframeRef} count={count} loading={loading} onRefresh={loadAndSend} />,
          },
          {
            key: 'saved',
            label: `Saved PDFs${files.length ? ` (${files.length})` : ''}`,
            children: (
              <SavedFilesTab
                rows={files}
                loading={filesLoading}
                busyId={busyId}
                isAdmin={isAdmin}
                userId={user?.id}
                editor={editor}
                onRefresh={loadFiles}
                onOpen={openFile}
                onSaveAs={saveFileAs}
                onDelete={deleteFile}
                onForceUnlock={forceUnlock}
              />
            ),
          },
        ]}
      />
    </div>
  );
}
