import { useEffect, useRef, useState } from 'react';
import { Button, Popconfirm, Space, Table, Tabs, Typography, message } from 'antd';
import { ApiClient } from '../api/apiClient.js';
import { useApp } from '../AppContext.jsx';
import { splitName } from '../utils/splitName.js';

const { Title, Text } = Typography;

// Maps a probationer (+ its psir_profile snapshot) onto the exact record
// shape renderer/public/records-check-generator/rc-render.js expects — see
// its FIELDS table. Birthdate is sent as a real Date (postMessage's
// structured clone preserves Date instances) since rc-render's fmtDate()
// only recognizes Date objects or Excel serial numbers, not ISO strings.
// LAST_NAME/FIRST_NAME/MIDDLE_NAME aren't part of that FIELDS table — they
// ride along just for the saved PDF's filename (see app-logic.js).
function buildRec(p) {
  const profile = p.psir_profile || {};
  const f = profile.fields || {};
  const name = (f.lastName || f.firstName || f.middleName)
    ? { lastName: f.lastName || '', firstName: f.firstName || '', middleName: f.middleName || '' }
    : splitName(p.full_name);
  return {
    NAME: p.full_name || '',
    'TRUE NAME': f.trueName || '',
    ALIAS: p.alias || '',
    SEX: p.sex || '',
    AGE: p.age != null ? String(p.age) : '',
    'CIVIL STATUS': p.marital_status || '',
    'DATE OF BIRTH': p.birthdate ? new Date(p.birthdate) : null,
    'PLACE OF BIRTH': '',
    'PRESENT ADDRESS': p.address || '',
    'PERMANENT ADDRESS': f.permanentAddress || p.address || '',
    'CRIMINAL CASE NO./S': p.case_number || '',
    OFFENSES: p.offense || '',
    COURT: p.court_branch || '',
    'NAME OF SPOUSE': f.spouse || '',
    'NAME OF FATHER': f.fatherName || '',
    'NAME OF MOTHER': f.motherName || '',
    IO: p.assigned_officer_name || '',
    BARANGAY: '',
    LAST_NAME: name.lastName,
    FIRST_NAME: name.firstName,
    MIDDLE_NAME: name.middleName,
  };
}

function GeneratorTab({ iframeRef, count, loading, onRefresh }) {
  return (
    <div>
      <Space align="center" style={{ width: '100%', justifyContent: 'space-between', marginBottom: 12 }}>
        <Text type="secondary" style={{ fontSize: 13 }}>
          {count} case{count === 1 ? '' : 's'} available — queue petitioners below, then save PDFs and/or print.
        </Text>
        <Button onClick={onRefresh} loading={loading}>Refresh Case List</Button>
      </Space>
      <div style={{ height: 'calc(100vh - 220px)', border: '1px solid #e6e9ee', borderRadius: 6, overflow: 'hidden' }}>
        <iframe
          ref={iframeRef}
          title="Records Check Generator"
          src="records-check-generator/index.html"
          style={{ width: '100%', height: '100%', border: 'none' }}
        />
      </div>
    </div>
  );
}

function SavedFilesTab({ rows, loading, busyId, isAdmin, onRefresh, onOpen, onSaveAs, onDelete }) {
  const recipients = [...new Set(rows.map((r) => r.recipient))].sort();

  const columns = [
    {
      title: 'Date', dataIndex: 'date_folder', key: 'date_folder', width: 120,
      sorter: (a, b) => a.date_folder.localeCompare(b.date_folder),
    },
    { title: 'Petitioner', dataIndex: 'probationer_name', key: 'probationer_name' },
    { title: 'Docket #', dataIndex: 'docket_number', key: 'docket_number', width: 150 },
    { title: 'Generated By', dataIndex: 'generated_by_name', key: 'generated_by_name', width: 170 },
    {
      title: 'Generated', dataIndex: 'generated_at', key: 'generated_at', width: 180,
      render: (v) => new Date(v).toLocaleString(),
      sorter: (a, b) => new Date(a.generated_at) - new Date(b.generated_at), defaultSortOrder: 'descend',
    },
    {
      title: 'Actions', key: 'actions', width: 280,
      render: (_, row) => (
        <Space>
          <Button size="small" loading={busyId === row.id} onClick={() => onOpen(row.id)}>Open</Button>
          <Button size="small" loading={busyId === row.id} onClick={() => onSaveAs(row.id)}>Save a copy as…</Button>
          {isAdmin && (
            <Popconfirm title="Delete this file?" onConfirm={() => onDelete(row.id)}>
              <Button size="small" danger>Delete</Button>
            </Popconfirm>
          )}
        </Space>
      ),
    },
  ];

  return (
    <div>
      <Space align="center" style={{ width: '100%', justifyContent: 'space-between', marginBottom: 12 }}>
        <Text type="secondary" style={{ fontSize: 13 }}>
          Shared across Head Office and Branch Office — {rows.length} file{rows.length === 1 ? '' : 's'} across {recipients.length} folder{recipients.length === 1 ? '' : 's'}.
        </Text>
        <Button onClick={onRefresh} loading={loading}>Refresh</Button>
      </Space>
      {recipients.length === 0 ? (
        <Text type="secondary">No PDFs saved yet — use the Generator tab to save some.</Text>
      ) : (
        <Tabs
          type="card"
          items={recipients.map((recipient) => {
            const recipientRows = rows.filter((r) => r.recipient === recipient);
            return {
              key: recipient,
              label: `${recipient} (${recipientRows.length})`,
              children: (
                <Table
                  rowKey="id"
                  loading={loading}
                  dataSource={recipientRows}
                  pagination={{ pageSize: 20 }}
                  columns={columns}
                />
              ),
            };
          })}
        />
      )}
    </div>
  );
}

export default function RecordsCheckView() {
  const { user } = useApp();
  const isAdmin = user?.role === 'admin';
  const iframeRef = useRef(null);
  const [loading, setLoading] = useState(false);
  const [count, setCount] = useState(0);
  const [files, setFiles] = useState([]);
  const [filesLoading, setFilesLoading] = useState(false);
  const [busyId, setBusyId] = useState(null);

  async function loadAndSend() {
    setLoading(true);
    try {
      const probationers = await ApiClient.get('/probationers');
      const list = probationers.map((p) => ({ id: String(p.id), name: p.full_name }));
      const rows = {};
      probationers.forEach((p) => { rows[String(p.id)] = buildRec(p); });
      setCount(list.length);
      iframeRef.current?.contentWindow?.postMessage({ type: 'rc:setMasterlist', payload: { list, rows } }, '*');
    } catch (err) {
      message.error(err.message);
    } finally {
      setLoading(false);
    }
  }

  async function loadFiles() {
    setFilesLoading(true);
    try {
      setFiles(await ApiClient.get('/records-check'));
    } catch (err) {
      message.error(err.message);
    } finally {
      setFilesLoading(false);
    }
  }

  async function openFile(id) {
    setBusyId(id);
    try {
      const { base64, filename } = await ApiClient.get(`/records-check/${id}/download`);
      await window.api.recordsCheckOpenFile(base64, filename);
    } catch (err) {
      message.error(err.message);
    } finally {
      setBusyId(null);
    }
  }

  async function saveFileAs(id) {
    setBusyId(id);
    try {
      const { base64, filename } = await ApiClient.get(`/records-check/${id}/download`);
      const result = await window.api.recordsCheckSaveFile(base64, filename);
      if (result.ok) message.success(`Saved to ${result.filePath}`);
    } catch (err) {
      message.error(err.message);
    } finally {
      setBusyId(null);
    }
  }

  async function deleteFile(id) {
    try {
      await ApiClient.delete(`/records-check/${id}`);
      message.success('Deleted.');
      await loadFiles();
    } catch (err) {
      message.error(err.message);
    }
  }

  useEffect(() => {
    loadFiles();
  }, []);

  useEffect(() => {
    function handleMessage(ev) {
      if (!iframeRef.current || ev.source !== iframeRef.current.contentWindow) return;
      const msg = ev.data;
      if (!msg || typeof msg !== 'object') return;

      if (msg.type === 'rc:ready') {
        loadAndSend();
      } else if (msg.type === 'rc:savePdfs') {
        const { files: toSave } = msg.payload || {};
        ApiClient.post('/records-check/batch', { files: toSave })
          .then((result) => {
            iframeRef.current?.contentWindow?.postMessage({ type: 'rc:saveResult', payload: { ok: true, count: result.count } }, '*');
            loadFiles();
          })
          .catch((err) => {
            iframeRef.current?.contentWindow?.postMessage({ type: 'rc:saveResult', payload: { ok: false, error: err.message } }, '*');
          });
      }
    }
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div>
      <Title level={3} style={{ margin: '0 0 12px' }}>Records Check</Title>
      <Tabs
        defaultActiveKey="generator"
        items={[
          {
            key: 'generator',
            label: 'Generator',
            children: <GeneratorTab iframeRef={iframeRef} count={count} loading={loading} onRefresh={loadAndSend} />,
          },
          {
            key: 'saved',
            label: `Saved PDFs${files.length ? ` (${files.length})` : ''}`,
            children: (
              <SavedFilesTab
                rows={files}
                loading={filesLoading}
                busyId={busyId}
                isAdmin={isAdmin}
                onRefresh={loadFiles}
                onOpen={openFile}
                onSaveAs={saveFileAs}
                onDelete={deleteFile}
              />
            ),
          },
        ]}
      />
    </div>
  );
}
